[project]
name = "primal-web-e2e"
version = "0.1.0"
description = "E2E-тесты Primal Web: pytest, Playwright, Allure"
authors = [
    {name = "Viktor", email = "evdokimov.viktor.91@mail.ru"}
]
requires-python = ">=3.14"
dependencies = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-playwright (>=0.9.0,<1.0.0)",
    "playwright (>=1.63.0,<2.0.0)",
    "allure-pytest (>=2.16.1,<3.0.0)",
    "httpx (>=0.28.1,<1.0.0)",
    "pytest-check (>=2.9.1,<3.0.0)"
]

[tool.poetry]
package-mode = false

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--alluredir=allure-results"
